### PR TITLE
Create hancestro.md

### PR DESCRIPTION
**Pull request by daniwelter**
hancestro.md to go with hancestro.yml in https://github.com/OBOFoundry/purl.obolibrary.org/pull/433

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Technically, this file and the PURL file look good.

I have one concern with this file: The Apache license is open source but OBO recommends Creative Commons licenses: http://obofoundry.org/principles/fp-001-open.html

I saw discussion of this ID request on the OBO mailing list earlier this year. It's not clear to me that the questions raised in that discussion have been addressed. @cmungall @lschriml @ramonawalls @Public-Health-Bioinformatics ?

**Comment by daniwelter** [comment]
I discussed this question with the rest of the ontology team at EBI and the general consensus was that all ontologies developed in our team use the Apache license, in line with the general EMBL-EBI licensing policy. Changing HANCESTRO to the Creative Commons license would require applying for wider approval within the institute.
@simonjupp may wish to comment?

**Comment by ramonawalls** [comment]
Changing the prefix from ancestro to hancestro, which makes it clearer that this is human oriented, does address my concern regarding the prefix. The labels for the ancestry category classes now make it clearer that they represent ancestry and not just countries.

There was some concern about all the place names having ancestro purls, rather than reusing existing classes. I see the the countries now come from DBpedia, but continent and region IDs are still local. I can't remember if there was a reason for not using GAZ here.

**Comment by Public-Health-Bioinformatics** [comment]
I recall there was some aversion to GAZ previously at EBI. But I'll note there is now a commitment to improve a variety of GAZ issues so perhaps its not too late to reconsider GAZ.

I was wondering though if there is still a plan to harmonize EFO ethnic group and hancestro?

**Comment by mellybelly** [comment]
Also see the NCIT demographic groups, we’ve been putting a lot of related content there.

On Jul 19, 2018, at 10:18 PM, Damion Dooley <notifications@github.com<mailto:notifications@github.com>> wrote:


I recall there was some aversion to GAZ previously at EBI. But I'll note there is now a commitment to improve a variety of GAZ issues so perhaps its not too late to reconsider GAZ.

I was wondering though if there is still a plan to harmonize EFO ethnic group and hancestro?

**Comment by cmungall** [comment]
I suggest @simonjupp or @mcourtot make a new ticket petitioning for fp-001 to include Apache, if EBI is not willing to change it's policy for non-software products. The implications of allowing Apache for ontologies are not clear to me.

**Comment by simonjupp** [comment]
@daniwelter we can release this under a CC-0

**Comment by daniwelter** [comment]
Great, I will update the ontology license and do a minor release in the next day or two.

**Comment by daniwelter** [comment]
I have done a minor release of HANCESTRO  today including updating the license to Creative Commons. I'm happy to include xrefs to related NCIt terms and any other relevant ontologies (eg GAZ countries) in the next version

**Comment by lschriml** [comment]
Great, I will be working on GAZ shortly, please let me know if you need anything. 

Cheers,
Lynn

**Pull request merged**
