### PR TITLE
Add Atom feed using the jekyll-feed plugin

### PR DESCRIPTION
**Pull request by ptgolden**
This adds an Atom XML feed for content under `_posts` using [jekyl-feed](https://github.com/jekyll/jekyll-feed). No additional install steps should be necessary since that plugin is pre-installed for [GitHub Pages](https://pages.github.com/versions/) and the [Jekyll Docker image](https://github.com/envygeeks/jekyll-docker/blob/fb892998d444b7b2e4074adeb032197f67853c0a/repos/jekyll/opts.yml#L22).

### CODE REVIEW

**Review by jsstevenson — APPROVED** [review]
👍 

I might suggest the `disable_in_development` setting because it looks like it adds about a second to build time (obviously that's not too bad, but it can add up), unless there's a good reason not to

**Comment by matentzn** [comment]
@ptgolden do you want to add the flag @jsstevenson suggests?

**Comment by ptgolden** [comment]
Done :+1:

**Comment by nlharris** [comment]
Can this be merged yet?

**Comment by jsstevenson** [comment]
(should be fine to merge imo)

**Review by matentzn — APPROVED** [review]
Let's try it

**Pull request merged**
