### PR TITLE
Update contact information for ARO to conform with FP11

### PR DESCRIPTION
**Pull request by cthoyt**
Currently, ARO violates FP11 (http://www.obofoundry.org/principles/fp-011-locus-of-authority.html) (based on my interpretation of it) because it uses a group email instead of denoting the single responsible person.

I've found the information for @raphenya via one of [his publications](https://www.mdpi.com/1999-4915/12/8/895) that lists his email address and added it as the contact information here. However, it appears Amogelang is a graduate student and might not be the ideal choice for a long term responsible contact person for the ontology. An alternative could be the corresponding author on ARO's [most recent publication](https://pubmed.ncbi.nlm.nih.gov/31665441/), Andrew G McArthur (@agmcarthur, mcarthua@mcmaster.ca).

Hopefully both of them can get in touch here and let us know how to proceed.

### CODE REVIEW

**Comment by matentzn** [comment]
Good initiative @cthoyt

**Comment by agmcarthur** [comment]
Hi @cthoyt, @raphenya is actually staff on CARD (and doing grad studies part-time at the moment), but I'm happy to be listed since I'm the project PI.

**Comment by cthoyt** [comment]
@agmcarthur thanks for the information. Before I make the updated, are you aware of the commitment of being the contact person?

From www.obofoundry.org/principles/fp-011-locus-of-authority.html:

> A primary contact person MUST be assigned. The name, email address and GitHub username of the contact person MUST be provided when requesting to register with OBO. The contact person MUST be subscribed to obo-discuss in order to be kept abreast of community developments of relevance to participating ontology projects, but the primary contact person can, of course, delegate these responsibilities for the project as necessary. The email address of the person who is the locus of the authority MUST be kept up-to-date, and before that person ceases to have responsibility for the project, they should identify a replacement and update the metadata accordingly (via the OBO Foundry issue tracker) before they move on.

**Comment by agmcarthur** [comment]
@cthoyt confirmed, I subscribe to obo-discuss and understand the commitment, please go ahead and make the update. Thanks!

**Review by matentzn — APPROVED** [review]

**Review by matentzn — APPROVED** [review]

**Pull request merged**
