### PR TITLE
WIP: Community pages

### PR DESCRIPTION
**Pull request by cmungall**
See #19

### CODE REVIEW

**Comment by matentzn** [comment]
Ah this is great! Very good idea. Once the schema is vetted by your reviewers I can create the community page for phenotype ontologies. It almost seems like a very shallow OBO foundry taxonomy against which the 151 OBO ontologies are tagged would be quite a simple way to generate these groupings you propose for the anatomy page automatically (and would be great for surveys too). Just a small one: There seems to be a mismatch between the ids listed under ontologies, and the ontologies mentioned later on. For example, fma, wbbt and fbbt are missing in the initial list. plana should be in there as well.

**Comment by cmungall** [comment]
good point, not sure why they were omitted

yes, we could do this by scraping the domain tag in the ontology metadata, but the idea here is that each community can be a bit more than the sum of ontologies, and they can 'annotate' the role of each ontology in the community

**Comment by mcourtot** [comment]
> It almost seems like a very shallow OBO foundry taxonomy against which the 151 OBO ontologies are tagged would be quite a simple way to generate these groupings you propose for the anatomy page automatically (and would be great for surveys too)


Yes! This would be very useful for us as we also wanted to leverage the 'domain' of each ontology to say things like "all values from this attribute are under the anatomical domain, so this attribute may be denoting an anatomical property and we should focus curation on this one'

I think there was some work done in @simonjupp team about this - Simon?

**Comment by cmungall** [comment]
Merging now as there is no links to it so it won't disrupt anything; once in master easier for others to propose changes

**Pull request merged**
