### PR TITLE
add section on OFOC minutes being open to public

### PR DESCRIPTION
**Pull request by nlharris**
I'm adding this as a strawperson draft; please feel free to suggest edits!

### CODE REVIEW

**Comment by nataled** [comment]
A few questions:
1) I'm unsure as to why this needs to be an SOP? It's really just information that (to me) belongs in some 'how do I participate' (or related) FAQ.

2) Do we normally include histories in the SOPs? Obviously we want to provide links, but why the other background information?

**Comment by nlharris** [comment]
1. I should have noted, this was in response to the request in https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2048#issuecomment-1328914773
2. In this case, I felt it was relevant to provide that (brief) history because I've seen so many cases where someone comes in later saying, "Wait, when/why did we agree to do this?". But if it doesn't seem needed, feel free to remove it.

**Comment by nlharris** [comment]
Removed history of public meeting minutes decision and also removed statement that OBO Ops meetings are open to the public, as it was agreed during today's meeting that this is not the case. Now there's just one added line.

**Review by nataled — APPROVED** [review]

**Review by matentzn — APPROVED** [review]

**Comment by nlharris** [comment]
Thanks. I'm not authorized to merge, so someone else will need to.

**Pull request merged**
