### PR TITLE
Update cl.md

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
update mailing list

### CODE REVIEW

**Review by nlharris — COMMENTED** [review]
If I go to groups.google.com/g/cl_edit, I get: Content unavailable. Try switching accounts, or check with your organization's administrator to make sure you have permission

**Review by matentzn — APPROVED** [review]

**Comment by matentzn** [comment]
@nlharris I can go to this page, I vote for merging (you can do it if you want).

**Comment by nlharris** [comment]
I can't merge because "The Travis CI build could not complete due to an error"

**Comment by matentzn** [comment]
I will take care of it when https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1269 is merged.

**Pull request merged**
