### PR TITLE
Add metadata validation test

### PR DESCRIPTION
**Pull request by rctauber**
See #663 

The new test is included in the Travis CI stuff, so that will fail as there are currently 54 violations.

### CODE REVIEW

**Comment by rctauber** [comment]
Current violations (with number of violating ontologies):
* missing 'contact' (11)
* missing 'description' (32)
* invalid 'license' values (6) *
* 'contact.label' is an email address instead of a name (3)
* 'product.id' is not an Ontology product (1) **
* 'homepage' has multiple values (1) ***

\* Auto-populating the license labels from the URLs which would help with this problem
\*\* ECO has a `.txt` product (mappings) - should all products be ontology format?
\*\*\* Could a project have more than one homepage, or should we require exactly one?

**Comment by cmungall** [comment]
Next step to fill in missing values? I can do some, @rvita can you help?

**Comment by cmungall** [comment]
I like making incremental progress - so how about temporarily relaxing some of the constraints so we can get the json-schema framework in place, and then gradually introducing them alongside necessary curation, a field at a time?

**Comment by jamesaoverton** [comment]
@cmungall I agree.

**Comment by rctauber** [comment]
See #740 for updated version.

**Pull request closed without merging**
