### PR TITLE
New usage examples and imports

### PR DESCRIPTION
**Pull request by pbuttigieg**
@cmungall apropos examples provided by @kaiiam

### CODE REVIEW

**Comment by cmungall** [comment]
I don't seen any examples of use of ENVO on the linked page?

**Comment by kaiiam** [comment]
> I don't seen any examples of use of ENVO on the linked page?

@cmungall in Planet Microbe we are using OBO terms to standardize the metadata of select marine 'omics projects. If you look at the ``Ontology Label`` and ``Unit`` columns you'll see that were employing a variety of OBO semantics to richly describe the data.

**Comment by cmungall** [comment]
@kaiiam - it looks like PM is removing the zero padding in the IDs this is a really bad idea can you follow up?

**Comment by kaiiam** [comment]
@cmungall what I think you are referring to is the value column, which was sourced form the data-stets themselves in this case OSD. We've added to that data the ``Ontology Label`` which is the full purl as annotation in this case biome http://purl.obolibrary.org/obo/ENVO_00000428. I had planned on further cleaning the datasets themselves to change them from (for example) ``estuarine biome (ENVO:1000020)`` to ``estuarine biome (ENVO_01000020)`` or ``estuarine biome http://purl.obolibrary.org/obo/ENVO_01000020`` or perhaps just the purl itself.  Let me know what you think it should be changed to. 

| Ontology Label | Dataset Label | Value |
| -- | -- | -- |
| [biome](http://purl.obolibrary.org/obo/ENVO_00000428) | Biome | estuarine biome (ENVO:1000020) |

**Comment by cmungall** [comment]
Right, this is the usage field for the ENVO record, so we want to record
non-trivial use of ENVO as values. It's great that PM is using OBO as field
descriptors too, we don't really have a place for this - though you could
make a small application ontology for this?

Cleaning up the fields would be great. Happy for them to remain CURIEs, but
you can link out using PURLs

**Comment by kaiiam** [comment]
The important usage of OBO terms (primarily envo) in planet microbe is for
semantic search based on dataset metadata. From our site:
https://www.planetmicrobe.org/project/#/search users can search based on
unified OBO semantics (see the Add Filter tab) for a variety of common
oceanography metadata such as concentration of chlorophyll, particulate
carbon, turbidity of water etc.

We do have an application ontology which you helped me to create which
imports form ENVO, OBI, IAO, UO etc. Bringing together a rich OBO semantic
layer for term annotation and standardization.

**Pull request merged**
