### PR TITLE
create ohmi.md

### PR DESCRIPTION
**Pull request by zhengj2007**
add md file for OHMI

### CODE REVIEW

**Comment by cmungall** [comment]
Will you do a PR for the purl?

**Comment by zhengj2007** [comment]
@cmungall  Yes. I just did it, see 
https://github.com/OBOFoundry/purl.obolibrary.org/pull/321

Anything else should I do for registration of OHMI in OBO?

**Comment by cmungall** [comment]
The final step is to run `make`, I usually do this, but good to have others in the @OBOFoundry/obo-admin team able to do this.

**Comment by zhengj2007** [comment]
@cmungall Thanks! 

I would like to run make in the future. Just wondering how to run it? Thanks!

**Pull request merged**
