### PR TITLE
Create detailed sop for roles #2236

### PR DESCRIPTION
**Pull request by erik-whiting**
This PR is the initial work for https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2236

Note all I did was add empty pages, there is no information here. Also note I called it "website coordinator" instead of "website maintainer" since the "coordinator" version seems to be favored everywhere else. Let me know if I should change it back or if anything else needs to change.

Thanks!

### CODE REVIEW

**Comment by matentzn** [comment]
Excellent! Lets leave this PR open in Draft mode, and I will keep adding to it over the next weeks whenever some new insight on SOPs comes up. This is great.

**Comment by deepakunni3** [comment]
Thanks @erik-whiting for starting this draft. And thank you @matentzn for adding the SOP for Metadata Steward 🙏

**Comment by matentzn** [comment]
@erik-whiting can we wrap this PR up?

**Comment by erik-whiting** [comment]
@matentzn I left it open because of your suggestion to do so here: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2238#issuecomment-1345519477

If you think it's ready to merge, it's ready to merge

**Comment by matentzn** [comment]
I think we didn't add much in a while so we may as well just merge it and iterate

**Comment by erik-whiting** [comment]
@matentzn cool, I just need you to "approve" the PR, I can't merge it otherwise (and can't approve it since I'm the PR author)

**Review by matentzn — APPROVED** [review]

**Comment by matentzn** [comment]
Thank you!

**Pull request merged**
