### PR TITLE
Adding pfabry photo

### PR DESCRIPTION
**Pull request by pfabry**

### CODE REVIEW

**Comment by matentzn** [comment]
@rays22 good to go. Feel free to merge

**Comment by rays22** [comment]
> @rays22 good to go. Feel free to merge

@matentzn , it seems that I am not [authorized](https://docs.github.com/articles/about-protected-branches/) to merge this pull request.

**Comment by erik-whiting** [comment]
> > @rays22 good to go. Feel free to merge
> 
> @matentzn , it seems that I am not [authorized](https://docs.github.com/articles/about-protected-branches/) to merge this pull request.

same, I feel like we both probably should be

**Comment by matentzn** [comment]
Can you try again? I think this was due to a severe branch protection rule.

**Pull request merged**
