### PR TITLE
Add publication to oba metadata.

### PR DESCRIPTION
**Pull request by rays22**
The Ontology of Biological Attributes (OBA) - Computational Traits for the Life Sciences

https://doi.org/10.1101/2023.01.26.525742

### CODE REVIEW

**Review by cthoyt — APPROVED** [review]
Great, thanks @rays22! Congratulations on getting your publication out 🚀

**Comment by rays22** [comment]
> Great, thanks @rays22! Congratulations on getting your publication out 🚀

Thank you, @cthoyt !

**Review by anitacaron — APPROVED** [review]

**Comment by cthoyt** [comment]
@deepakunni3 can you please merge this

**Comment by deepakunni3** [comment]
@rays22 Thank you for taking the lead and merging this PR 👍

@cthoyt Apologies for the delayed response. I have merged the updated metadata and the website is now up-to-date with the changes from this PR

**Pull request merged**
