### PR TITLE
Update Slack link

### PR DESCRIPTION
**Pull request by nlharris**
to the one that actually lets you join w/o an invitation (hopefully this won't attract spam)

### CODE REVIEW

**Comment by nlharris** [comment]
anyone want to review this?

**Review by matentzn — COMMENTED** [review]
If this is a permanent join link, won't this make the slack space vulnerable to Spam? 

As an aside; I didn't know you could create permanent invite links! I thought they expire after 30 days!

**Comment by nlharris** [comment]
> If this is a permanent join link, won't this make the slack space vulnerable to Spam?

That is a risk. However, we have had the permanent join link on our website already for a year or so; this PR is just updating the link in the other various places it appears. So far, I have not been aware of any spammers joining the Slack. (If they do, we can ban them.)

> As an aside; I didn't know you could create permanent invite links! I thought they expire after 30 days!

**Review by matentzn — APPROVED** [review]
In this case, let's go do it.

**Pull request merged**
