### PR TITLE
rename Recommendations to Recommendations/Requirements

### LINKED ISSUE #1251: Use of "Recommendation" in Principle pages
On the Principle pages we have a section name "Recommendation".  This makes it seems like the content under this is optional. I think this is too weak. We need stronger wording.

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
closes #1251

### CODE REVIEW

**Review by nlharris — COMMENTED** [review]
Maybe this ship has already sailed, but I'm wondering if it makes more sense to mention Requirements first, since they are more important than Recommendations? I would say "Requirements and Recommendations" (in case the / was somehow confusing -- like, we're supposed to divide Recommendations by Requirements, what??)
But if this was already agreed upon, then carry on!

**Comment by nicolevasilevsky** [comment]
Sounds good to me. @nataled and @lschriml let us know if there are any objections. I'll go ahead and make this change.

**Review by nlharris — APPROVED** [review]

**Comment by nataled** [comment]
I was aiming to keep the section title as short as possible, as all others are single words. My personal preference is to keep it as it was, as the words just flow more easily to me, the change is less jarring (in that it keeps the original title word in the original position), and other reasons. But, it seems that the changes have already been made, so don't bother changing back.

In the future, please don't override decisions made during discussions. Suggestions are fine, as these will then be further discussed.

**Comment by nicolevasilevsky** [comment]
Ok, got it! It's just the push of a button to change it back though, it will only take a second, so whatever you prefer.

**Comment by nataled** [comment]
I see. Well, our protocol is to discuss all suggestions, so it's not a matter of my personal preference. We can continue discussion next meeting. For now I suppose we should not make public changes to the section title.

**Comment by nlharris** [comment]
Let's just leave this section header as is. If we close this PR, will that leave things as-is?

**Comment by nicolevasilevsky** [comment]
It currently reads "Recommendations". If we close this PR, it will stay as such.

**Comment by nlharris** [comment]
Ok. We should make it what was agreed on, which I think was Recommendations/Requirements

**Comment by nlharris** [comment]
so we should close this PR, right?

**Comment by nataled** [comment]
I understood this to need more discussion, which will be done at the next EWG meeting. The specific changes needed for this ticket have been done (even if they might need to be re-done later) but have been put on hold pending the outcome of that discussion.

**Comment by nicolevasilevsky** [comment]
We updated the headers to:
Recommendations and Requirements

We discussed this on the 03/02/21 call and all agreed on this.

@nlharris if this looks okay to you, can you merge? thanks!

**Review by nlharris — APPROVED** [review]
looks good

**Pull request merged**
