### PR TITLE
Removed link to out-of-date Setting Up Protege page

### PR DESCRIPTION
**Pull request by nlharris**
replaced with link to /resources
This partially addresses #476

### CODE REVIEW

**Comment by matentzn** [comment]
@jamesaoverton Can you review this one? I am just wondering how this change can theoretically work.. How would the Github pages find the GitHub relative link to /resources.md?

**Review by jamesaoverton — APPROVED** [review]
This is the correct way to link to <http://obofoundry.org/resources>

**Comment by matentzn** [comment]
Cheers

**Comment by nlharris** [comment]
Sorry, @jamesaoverton -- I thought I'd seen other relative URLs. Thanks for fixing.

**Comment by matentzn** [comment]
No you did it correctly! James just told me your solution was correct!

**Pull request merged**
