### PR TITLE
create vbo.md

### PR DESCRIPTION
**Pull request by sabrinatoro**
This is related to this issue https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1883

### CODE REVIEW

**Comment by cthoyt** [comment]
Would be nice to finish https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1841 before admitting new ontologies - @sabrinatoro maybe you can be a bit proactive about this

**Comment by matentzn** [comment]
Yes absolutely, I think @sabrinatoro you and I can spearhead this together and permeate it through the entire community.

**Review by matentzn — APPROVED** [review]

**Comment by matentzn** [comment]
fixes #1883

**Comment by cthoyt** [comment]
This was merged without the existence of an OBO PURL configuration. Isn't this required? Why isn't there an automated test for this?

does not exist -> https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/vbo.yml

**Pull request merged**
