### PR TITLE
rename file to register instead of submit

### PR DESCRIPTION
**Pull request by nicolevasilevsky**

### CODE REVIEW

**Comment by jamesaoverton** [comment]
This file name / URL is not as important as the one we had trouble with earlier, but I still don't see the need to change it. Just changing the page `title:`, the content, or the text of the links to the page are all options that don't break links. If the URL says "submit" and the page says "register", I don't think anyone will complain.

In my opinion "register" is not significantly more clear than "submit", but I don't feel strongly about it.

**Comment by nicolevasilevsky** [comment]
@jamesaoverton 
the Submit your ontology link under participate takes you to http://www.obofoundry.org/faq/how-do-i-register-my-ontology.html, which is currently broken. 

I think this PR will fix this (but I'm not 100% sure). 

image

**Review by jamesaoverton — APPROVED** [review]
You're right, I got mixed up. When I look at the GitHub history for a month ago, the file was called `faq/how-do-i-register-my-ontology.md`:

https://github.com/OBOFoundry/OBOFoundry.github.io/tree/02cce6c45a5cac0d580b84019cfa6428a092bf03/faq

I'd prefer to rename it back to "register", which is what this PR does.

**Comment by nicolevasilevsky** [comment]
@jamesaoverton should I merge this?

**Comment by jamesaoverton** [comment]
Yes. Unless you need feedback from someone else, or you want to merge other PRs first.

**Comment by nicolevasilevsky** [comment]
@jamesaoverton actually, I did the same edit on #1301, so this change will be implemented when that PR is merged. (I'm not sure what will happen if these two PRs are both merged, would it create conflicts?)

Do you know if #1301 is close to being approved/merged?

(There was some confusion, hence I created this duplicated PR.)

**Pull request merged**
