### PR TITLE
DO NOT MERGE: Proposed extension to FP2 for alerting stakeholders to changes

### PR DESCRIPTION
**Pull request by cmungall**

### CODE REVIEW

**Comment by nataled** [comment]
From OFOC 2021-11-30 meeting: this PR will be abandoned in favor of crafting a new principle.

**Comment by cmungall** [comment]
where is the ticket link?

**Comment by nataled** [comment]
@cmungall no ticket link yet, as we (the EWG) want to have some straw man text in place first. We are close to getting there.

**Comment by nataled** [comment]
Ticket for this is #1715, which references the draft PR #1714. Closing this ticket in favor of further discussion there.

**Pull request closed without merging**
