### PR TITLE
Populate repository fields based on tracker/homepage fields

### LINKED ISSUE #848: Add explicit github repo field
Currently it's possible to get the gh repo from the issues field (if GH is used).

It would be good to have an explicit field for this

In case it's helpful to anyone (or myself when I try this again), I used this horrible hack to check out all repos:

```
grep -h tracker ontology/*md | perl -npe "s@.*https://github.com/@git clone gitATgithub.com:@;s/gitAT/git@/;s@/issues@@" | grep ^git
```

### PR DESCRIPTION
**Pull request by cthoyt**
Closes #848

This PR adds a simple [python script](https://github.com/cthoyt/OBOFoundry.github.io/blob/populate-repos/util/populate_repositories.py) that reads the configuration files and automatically updates their repository field if it's missing.

### CODE REVIEW

**Review by matentzn — APPROVED** [review]

**Comment by cthoyt** [comment]
FYI this shouldn’t conflict with #1566

**Comment by matentzn** [comment]
This is all fine. Note I don't like trackers being removed (like VSAO), but it's ok in that case as it is an obsolete.

**Comment by matentzn** [comment]
Thank you very much @cthoyt for your ongoing amazing support and help with everything!

**Review by jamesaoverton — APPROVED** [review]

**Comment by jamesaoverton** [comment]
Thanks @cthoyt! I looked through the changes carefully. The script has appropriately narrow scope: If the 'repository' field is not present, but the 'tracker' or 'homepage' fields start with "https://github.com/", then try to guess the 'repository'. I'm very confident that this improves the quality of the OBO metadata in a safe way, so I'm going to merge it.

**Pull request merged**
