### PR TITLE
Curate RORs for operations committee

### LINKED ISSUE #2127: Curate ROR identifiers for OBO Operations committee members
The [Research Organization Registry](https://ror.org/) gives actionable identifiers for organizations, for example, https://ror.org/02jbv0t02 for Lawrence Berkley National Labs. It would be nice to curate the ROR for each operations committee's affiliation by creating a new field `ror` for each person in https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/_data/operations.yml.

For example, for Chris Mungall, you can add `ror: 02jbv0t02`

### PR DESCRIPTION
**Pull request by cthoyt**
As a follow-up to https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2131, this PR closes #2127 by adding RORs for all OBO operations committee members. For the case of Nico and James whose primary affiliations are companies, I tried doing ROR requests (https://github.com/ror-community/ror-updates/issues/1735 and https://github.com/ror-community/ror-updates/issues/1737) but these were rejected due to one-person companies being out of scope for ROR, so I made Wikidata identifiers instead.

## Benefits of RORs

There are lots of typos and inconsistencies in the affiliations written so far - RORs are a nice way of being able to programatically look up information about affiliations (e.g., country, city) and assigning a canonical name. These will be useful for some of the OBO Foundry community summaries I've been developing.

## Drawbacks of RORs

It's explicitly out of scope for ROR to model internal organizational structure (so no colleges, departments, etc can get RORs) so it's not super granular.

### CODE REVIEW

**Comment by cthoyt** [comment]
@matentzn it's ready

**Review by matentzn — APPROVED** [review]
Excellent @cthoyt!

**Comment by addiehl** [comment]
I notice you listed Barry Smith as being affiliated with the University of Florida, but he is actually affiliated with the University at Buffalo. You might want to fix this.

**Comment by cthoyt** [comment]
Wasn’t me! If you want to fix it a pr would be welcome

**Comment by balhoff** [comment]
I'm pretty sure the Florida tag is in Bill's entry; the ordering is just a little confusing optically.

**Comment by addiehl** [comment]
I see now that that Jim is correct and the blue lines are not separators between entries.

**Pull request merged**
