### PR TITLE
Create proco.md

### PR DESCRIPTION
**Pull request by matentzn**

### CODE REVIEW

**Comment by matentzn** [comment]
Moving to draft while waiting for formal decision during the next OBO Ops call.

**Comment by matentzn** [comment]
@nataled @bpeters42 need one approval else cant merge.

**Review by bpeters42 — APPROVED** [review]

**Comment by cthoyt** [comment]
V disappointing this was merged while tests were failing. @matentzn how was this even possible?

**Comment by cthoyt** [comment]
@matentzn there is a setting to make sure branches are up-to-date with the main branch before merging. This should be enabled to make sure if a branch hasn't been synced, that its outdated tests aren't giving a false positive

**Comment by matentzn** [comment]
HOW on earth are you not.. asleeeeeep! :D 

Tests passed, I just didn't realise that it was not up to date from master

**Comment by nlharris** [comment]
Charlie never sleeps! 😀

**Comment by cthoyt** [comment]
it's only 22.47 here!

**Comment by matentzn** [comment]
When I saw master breaking I got really scared Charlie would come and eat me alive :D I was hoping you would only notice after its fixed..

**Pull request merged**
