### PR TITLE
Update hp.md

### PR DESCRIPTION
**Pull request by drseb**
Add HL7 as user of HPO

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
@drseb Chris said usages is currently for usages in a database, such as monarch or a MOD. He didn't want me to add HL7 as a usage for Mondo.

**Comment by drseb** [comment]
ok. so should I close this PR?

**Comment by nicolevasilevsky** [comment]
Yeah, I think so

**Comment by drseb** [comment]
thanks

**Pull request closed without merging**
