### PR TITLE
Update mp.md

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
added mailing list info

### CODE REVIEW

**Comment by cmungall** [comment]
@sbello - ok with this addition to your page?

**Comment by cmungall** [comment]
@nicolevasilevsky can you resolve the conflicts?

**Comment by nicolevasilevsky** [comment]
I think I resolved the conflicts. I added the mailing list on another PR (#726)

**Comment by jamesaoverton** [comment]
Already fixed by #726

**Pull request closed without merging**
