### PR TITLE
OLD: Portals

### PR DESCRIPTION
**Pull request by matentzn**
This is an old, unmerged branch. We will merge or delete this.

### CODE REVIEW

**Comment by nlharris** [comment]
Merge or delete?

**Comment by matentzn** [comment]
I would not delete this yet - seems like a lot of work went into it..

**Comment by cthoyt** [comment]
A lot of the content in this PR is now part of the ontologies themselves in their domain annotations.

**Comment by matentzn** [comment]
Yes, the idea of this PR was to create landing pages for these domains.. Something like having a landing page for obo/anatomy, listing all related ontologies and adding some fluff around these domains (manually curated pages!) with nice pictures, principles, links to overarching docs for design patterns etc..

Needs a shove. Interesting issue though.

**Comment by matentzn** [comment]
Time to close

**Pull request closed without merging**
