### PR TITLE
Mark CMF as obsolete

### PR DESCRIPTION
**Pull request by matentzn**
see #794

### CODE REVIEW

**Comment by cthoyt** [comment]
Is setting the activity status to "orphaned" also appropriate here?

**Comment by matentzn** [comment]
The authors say they are working on a new version - `orphaned` invites people to take over.. So I would say no.

**Comment by cthoyt** [comment]
Oh, okay. I don't think that information comes from any public place, though. The authors marked as responsible on CMF didn't engage in conversation on #794

**Comment by matentzn** [comment]
yeah, @nicolevasilevsky reached out and thats the information she got..

**Review by cthoyt — APPROVED** [review]

**Pull request merged**
