### PR TITLE
update upheno.md

### PR DESCRIPTION
**Pull request by rvita**
per obo services grant, updated contact, homepage, description, and license

### CODE REVIEW

**Comment by jamesaoverton** [comment]
The license label does not match the license URL -- which is it?

**Comment by cmungall** [comment]
@vasilevsky @dosumis @mellybelly - I suggest we go with CC-0

**Comment by mellybelly** [comment]
+1 on CC-0

**Comment by jamesaoverton** [comment]
Fixed by #727

**Pull request closed without merging**
