### PR TITLE
Update cdno.md file again

### PR DESCRIPTION
**Pull request by LilyAndres**
This step is made just to update the latest version of the cdno.owl file, as I think I had the incorrect version when I made a pull request last month, sorry about that. Hopefully now we can see the updated name Compositional instead of Crop.

### CODE REVIEW

**Comment by cthoyt** [comment]
The diff in the file is just the removal of a blank line. Is something missing?

**Comment by LilyAndres** [comment]
@cthoyt no, everything is the same. I just think I had to do the pull request again so the last release of the cdno.owl file is updated in obo, as I think OBO repo has the last version of the CDNO https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1536#issuecomment-858256953

**Comment by LilyAndres** [comment]
@cthoyt I'm sorry probably there is no need to merge the md file then?

**Comment by matentzn** [comment]
@LilyAndres can you explain what problem you are experiencing? OBO should have nothing to do with your ontology versions etc...

**Comment by LilyAndres** [comment]
@matentzn yes, thanks I tagged you in my issue https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1541

**Review by jamesaoverton — APPROVED** [review]

**Comment by cmungall** [comment]
can we close this? It looks like the PR is just a one-line change removing an empty line

**Pull request merged**
