### PR TITLE
Improve JSON-LD context export

### LINKED ISSUE #2410: JSON-LD context does not expand as intended
https://purl.obolibrary.org/meta/obo_context.jsonld

We can't have trailing underscores on expansions (and have it behave as expected). Sorry, I don't make the rules

More context here:

- https://github.com/w3c/json-ld-syntax/issues/329

These would all have to be modified to be nested

```json
      "RO": {
         "@id": "http://purl.obolibrary.org/obo/RO_",
         "@prefix": true
      }
```

### PR DESCRIPTION
**Pull request by cthoyt**
Closes #2410 by using the `@id`/`@prefix` combination, which is required since JSON-LD technically doesn't support URI prefixes that end with an underscore `_`

cc @cmungall

### CODE REVIEW

**Comment by matentzn** [comment]
@jamesaoverton do you know any specific reason not to do this? It was requested by @cmungall and it is the "correct" thing to do. My gut feeling is wave it through, roll back if something breaks, but if you already kNOw something will break we might as well fix it first.

**Review by balhoff — APPROVED** [review]
Thanks!

**Comment by jamesaoverton** [comment]
This change is necessary, I guess, but quite annoying. We have a bunch of tools that predate the changes to JSON-LD that assume prefixes have to end with selected characters. We pushed back on that design decision but they ignored us.

ROBOT packages `obo_context.jsonld` and uses it for the default set of prefixes. I simply copied this file into ROBOT and that broke the unit test suite: <https://github.com/ontodev/robot/pull/1170>. I haven't looked any deeper, and I won't have time for at least a week. If someone else can step up, that would be great.

Since we have to make this change, and we'll have to fix our workflows anyway, I think that this PR should also add the `obo` prefix as requested in #2462.

**Comment by jamesaoverton** [comment]
Sorry, I was wrong. Another 5 minutes of looking into this and I see that ROBOT does not just use the `obo_context.jsonld` but adds several common prefixes to it. When I restored those, the test suite passed again: https://github.com/ontodev/robot/pull/1170/commits/4f1af7e5030d6dbaff8a5bedfb54e6cedc574e54.

**Comment by jamesaoverton** [comment]
Ok the upshot is that ROBOT will need a minor update to handle this change before the next release. Not a problem.

This reassures me that our workflows should not break as long as they are using JSON-LD libraries to work with the context file, and not doing it with custom code.

**Review by jamesaoverton — APPROVED** [review]
I tested with ROBOT and this looks good. Thanks!

Since we're already changing the context, this would be a good time to add the `obo` prefix, as requested in #2462.

**Comment by cthoyt** [comment]
@jamesaoverton I am happy to add that in either this PR or a follow-up one. Maybe there are other reservations, though, based on the discussion in https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2462

**Review by matentzn — APPROVED** [review]
Lets see what breaks!

**Pull request merged**
