### PR TITLE
Update and rename epso.md to epio.md

### PR DESCRIPTION
**Pull request by phwegner**
Changed repository and renamed EPSO to EPIO. So we need a new namespace "EPIO" instead of "EPSO" due to redundancy. (EPSO already exists). Sorry for the circumstances. I will also edit the purl file.

### CODE REVIEW

**Comment by matentzn** [comment]
That is much more complicated. This will probably take months as it will need another round of review and some discussion at the OBO committee..

**Comment by matentzn** [comment]
Can you point us to the place where EPSO exists?

**Comment by phwegner** [comment]
https://github.com/SCAI-BIO/EpilepsyOntology (New)
https://github.com/phwegner/Epilepsyontology (Ols)

**Comment by phwegner** [comment]
But concerning the revision. It is the exact same file but another name and another place.

**Comment by phwegner** [comment]
@matentzn Can we then stick to EPSO until EPIO is approved ?

**Comment by matentzn** [comment]
No I mean, why do we have to change the prefix?

**Comment by phwegner** [comment]
One of our team members notified us that EPSO is already taken by another Ontology. So not in OBO obviously but the abbreviation itself is already in use.

**Comment by matentzn** [comment]
Can you show us which one?

**Comment by phwegner** [comment]
https://bioportal.bioontology.org/ontologies/EPSO

**Comment by phwegner** [comment]
Even though Satya is a collaborator with the OBO EPSO Ontology those are two distinct Ontologies...

**Comment by matentzn** [comment]
What about all the IDs in EPSO, the term idsyy did you change them as well?

**Comment by phwegner** [comment]
We are doing that right now. So in the meantime will we stay with the EPSO namespace?

**Comment by matentzn** [comment]
I think your request may be valid enough to sort it out.. :/ Give us a day to discuss this.

**Comment by phwegner** [comment]
Thank you very much !

**Review by matentzn — APPROVED** [review]

**Comment by matentzn** [comment]
We reviewed this case and decided to approve it due to its _very specific_ circumstances. Generally, such requests will not approved, because there are a lot of architectural and conceptual problems that come with it. The specific circumstances for allowing this prefix change are:

- EPIO was only accepted recently and its identifiers are therefore unlikely to be reduced widely
- The conflicting Bioportal ontology is very similar in scope and  likely this will cause a lot of confusion for users of biomedical ontologies as a whole

Please confirm the following to things and I will merge the PR
- [ ] [This](https://bioportal.bioontology.org/ontologies/EPIO) is you
- [ ] You have migrated all your terms from EPSO ids to EPIO Ids

Once you confirm both, we will deal with the rest. Thanks

**Comment by phwegner** [comment]
Thank you for the fast response! 

I can confirm both I just added the correct ids and added the respective release. 
The version in bioportal is ours.

**Pull request merged**
