### PR TITLE
Changing tracker for ddanat

### PR DESCRIPTION
**Pull request by cmungall**
See https://github.com/dictyBase/migration-data/issues/5

### CODE REVIEW

**Comment by pfey03** [comment]
@cmungall I just updated ddanat. Added one term. Updated so rarely, I hope it's fine to just live where we have all our ontologies 
https://github.com/dictyBase/migration-data/blob/master/ontologies/dicty_anatomy.obo

**Comment by balhoff** [comment]
@pfey03 do you maintain ddanat elsewhere and copy to that repo? Just wondering because I wanted to point out my pull request there: https://github.com/dictyBase/migration-data/pull/12

**Comment by pfey03** [comment]
@balhoff no, you are correct and I only maintain it in dictyBase/migration/data.  

A couple years ago Chris asked to put it in another repo but that didn't suit us since this ontology so rarely changes and we need it in the current repo for our new emerging database.

**Comment by balhoff** [comment]
Okay, thanks—if you can merge that pull request it would be an improvement for GO. But if it is a problem, let me know and maybe we can discuss.

**Comment by pfey03** [comment]
I merged the pull request. 
Also, about adding xrefs to ddanat: Will you update the ontology so it doesn't cause problems in GO, and maybe also in UPHENO? If you do please let me know.

**Comment by pfey03** [comment]
Ah, I saw already through the merge, the xrefs. I'll update my own ontology with that and on our old database to be everywhere the same, thanks!

**Pull request merged**
