### PR TITLE
First draft of PPO registry entry, see #340

### PR DESCRIPTION
**Pull request by jamesaoverton**

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Hi @ramonawalls. This is a draft. Please make any edits required and fix the TODOs. A license would also be good.

Let me know when it's ready and I'll merge this and the PURL entry: https://github.com/OBOFoundry/purl.obolibrary.org/pull/278

**Comment by ramonawalls** [comment]
Hi @jamesaoverton. I think it is ready to go now. I added a description and license.

**Comment by jamesaoverton** [comment]
There should also be a description at the bottom after the `---`. It's in Markdown format and can be longer than the description above. For example see https://raw.githubusercontent.com/OBOFoundry/OBOFoundry.github.io/master/ontology/obi.md

**Comment by ramonawalls** [comment]
Ah, okay. I will add that now.

------------------------------------------------------
Ramona L. Walls, Ph.D.
Senior Scientific Analyst, CyVerse, University of Arizona
Research Associate, Bio5 Institute, University of Arizona

**Comment by ramonawalls** [comment]
Longer description added.

**Pull request merged**
