### PR TITLE
Update fp-010-collaboration.md

### PR DESCRIPTION
**Pull request by nlharris**
(had old sourceforge address)

### CODE REVIEW

**Comment by wdduncan** [comment]
@jamesaoverton the EWG has reviewed and approved. Can you please approve and merge.

**Comment by jamesaoverton** [comment]
@wdduncan I approved this and merged it, but everyone on the [OBO-admin](https://github.com/orgs/OBOFoundry/teams/obo-admin) team has permission to do so, including you.

Sometimes GitHub recommends a reviewer, usually because that person has reviewed a lot of other PRs. But that's just a recommendation and that person (me in this case) doesn't get a special notification or anything. I expected another editorial person to review this. In general, I only look at technical PRs.

**Comment by wdduncan** [comment]
@jamesaoverton Thanks for the info. I was going to my admin privileges to merge it, but I didn't know if that would break protocol. In the future, I will merge changes approved by the EWG even when you tagged as reviewer :)

**Comment by jamesaoverton** [comment]
@wdduncan Now that I think about it, I can't remember this workflow ever being demonstrated on an Operations call. I'm chairing the next call (September 8), so I've added that to the agenda. After the demonstration we can discuss any desired changed, and decide the best way to document the workflow for the future.

In the meantime, here's how I would describe the workflow:

Any OBO-admin could have reviewed this PR -- except for Nomi, because she created it. The OBO-admin team includes 22 people, and should include everyone on the larger Operations Committee. So the responsibility is widely shared, and not limited to GitHub's recommended reviewers.

You review a PR by:

1. clicking the "Files changed" tab, and reading through the changes
2. clicking the green "Review Changes" button in the top right of the tab, and marking the PR as "Approved" (or asking for changes)

Once there's at least one Approved review, the "Merge" button will be green, and any OBO-admin can merge the PR (including the PR's creator).

Without at least one Approved review, the "Merge" button is red and says something like "Use your administrator privileges to merge". We don't want to press the red button. We want to review the PR so that the Merge button is green, then merge.

**Pull request merged**
