### PR TITLE
add usage tag for WBphenotype

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
addresses #903

### CODE REVIEW

**Comment by nicolevasilevsky** [comment]
@cmungall thanks for the clarification.
- I updated the text about Monarch for WBphenotype
- I added WormBase as a user
- cc'ing @chris-grove to sign off on this (@chris-grove let me know if you need more details, see ticket #903)

**Comment by chris-grove** [comment]
@nicolevasilevsky 
Thanks. I agree with @cmungall that the Monarch usage tag for WBPhenotype should change from

"description: WBPhenotype is used by the Monarch Initiative for phenotype annotations."

to something like Chris suggests:

"description: Monarch integrates phenotype annotations from sources such as WormBase, and allows for querying using the WBPhenotype ontology"

**Comment by cmungall** [comment]
Thanks! Nicole can you change https://www.wormbase.org/#012-34-5 to
https://www.wormbase.org/

**Comment by nicolevasilevsky** [comment]
@cmungall done

**Pull request merged**
