### PR TITLE
Update RoleNORManager.md to include instructions regarding community …

### PR DESCRIPTION
**Pull request by nataled**
…suggestions

Added to the 'response to submitters' letter. Note: the original wording given here does not completely match recent communications with submitters, so there is a possibility that the additions given here must be reproduced elsewhere.

The additions were suggested [here](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2459#issuecomment-1755910058) and approved by @pfabry in a followup comment.

### CODE REVIEW

**Review by nlharris — APPROVED** [review]

**Comment by nlharris** [comment]
@pfabry do you have time to take a look at this?

**Review by pfabry — APPROVED** [review]
I agree with the changes.

**Comment by nataled** [comment]
@pfabry there is some question regarding the 'response to submitters' letter. I noticed that the original wording upon which my revisions were based does not completely match your recent communications with submitters. That raises the possibility that there is another version of the letter and, as a consequence, the additions given here must be reproduced elsewhere.

**Comment by pfabry** [comment]
> @pfabry there is some question regarding the 'response to submitters' letter. I noticed that the original wording upon which my revisions were based does not completely match your recent communications with submitters. That raises the possibility that there is another version of the letter and, as a consequence, the additions given here must be reproduced elsewhere.

@nataled Just to be sure we are on the same page, I use [this](http://obofoundry.org/roles/nor-manager) template for the response to submitter. I understand that this is the template that will be modified by the present PR. Is the concern about the mention of the `versioning` flag?

**Comment by nataled** [comment]
Hi @pfabry,

Yes, that's one of the differences between the role SOP and what has been used to communicate with submitters in practice. There are other differences as well. The differences were fairly minor, but it was hard to tell if there were two places the letter was kept, or if you've been modifying each time. Now that I know there is only a single place, I now need to know if the version in the role SOP should be updated with the version used in practice. If you think it should, I'll go ahead and make the revisions.

**Comment by pfabry** [comment]
Hi @nataled  
I just checked in the OBO operation minutes and there is a decision to "Not make resolvable versionIRIs mandatory" for the NOR Dashboard dating back to January 9. I think this could indeed be added to the response to submitter template. Thank you!

**Comment by nataled** [comment]
Will merge this and create a new PR to make other changes.

**Pull request merged**
