### PR TITLE
Update doid.md

### PR DESCRIPTION
**Pull request by aellenhicks**
Added an additional publication

### CODE REVIEW

**Review by matentzn — APPROVED** [review]

**Review by matentzn — APPROVED** [review]

**Comment by lschriml** [comment]
@aellenhicks and @matentzn -- I have updated the DO citation. As a policy, I do not think it appropriate for members of the OBO Foundry who are not the projects editor or PI to update the publications that should be cited for an ontology project.
Instead, a ticket should be opened with the suggested citation. 
Cheers,
Lynn

**Comment by cthoyt** [comment]
@lschriml disagree - such a policy would discourage community members from helping maintain the OBO Foundry. What happens if the ontology's contact person is unresponsive (as a very large number of them have demonstrated to be)? As the GitHub handle of _all_ ontologies' contact people are available, I think a better thing to do would be to flag updates to any given ontology with the contact person so they have the chance to get involved, otherwise our metadata overlords like @matentzn can make an executive decision to merge without them if they're unresponsive for too long, or if the change is not controversial.

**Comment by matentzn** [comment]
Oh, I thought that @aellenhicks was part of your team @lschriml - never thought anyone would ever bother to update the contents of a record otherwise! I think it makes sense to tag the contacts and give them 72 hours to take a look - obviously we will forget that occasionally, but we can try for it. And, if after 72 hours no response is there, we just merge. Sounds like a compromise?

**Comment by lschriml** [comment]
@matentzn --  yes, a good compromise. 
     Agree it is great to keep the ontology files updated.
And to coordinate with the project editor/PI.

Cheers,
Lynn

**Comment by lschriml** [comment]
@cthoyt @matentzn 
   Agreed, we should actively encourage community members in helping maintain the OBO Foundry. 

I think we can be a bit cautious here in how we deliver that help, to offer advice and solutions, at the same 
time to respect the developers of a project and their choices on what to include in their ontology. 

   I am concerned that if we change things in others ontologies, without their knowing about it, that this may discourage people joining the OBO Foundry, or being concerned that they are not involved. Or that developers may feel the OBO Foundry is overstepping. 

  From my own experience, as a PI of a two decades old project, I have responsibilities to my users and to my funders for what is included in the ontology and how it is presented, thus I take in all suggestions, but do review them before integration. 

Perhaps we can come together and formulate guidelines, to be shared with the OBO Foundry members, 
   such as: 
     A suggestion to be followed by a time period for PIs/editors to respond to the suggestion. 
           And clarifying what types of updates the OBO Foundry would involve. 
   As a measured approach, that continues to involve the PI/editor in the OBO Foundry efforts.  


Cheers,
Lynn

**Comment by lschriml** [comment]
@matentzn  -- can do.

**Pull request merged**
