### PR TITLE
Added link to google sheet checklist

### LINKED ISSUE #1339: Add link to Nicole's MORRC scoring spreadsheet
@nicolevasilevsky made a google spreadsheet for the Minimum Ontology Registration Request Checklist (MORRC) described on https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md

We should save a blank copy of Nicole's spreadsheet for future use, and point to it from the MORRC page. I can do that, if others agree.

See also related issue #1322

### PR DESCRIPTION
**Pull request by nlharris**
fixes #1339

### CODE REVIEW

**Review by matentzn — APPROVED** [review]
Very nicely formatted checklist!

**Comment by nlharris** [comment]
> Very nicely formatted checklist!

It's 90% Nicole's work!

**Comment by matentzn** [comment]
Thank you both :)

**Comment by nlharris** [comment]
> Some checks haven’t completed yet
> 1 expected and 1 successful checks

How long do these checks typically take? More than 5 hours?

**Pull request merged**
