### PR TITLE
Create afpo.md

### PR DESCRIPTION
**Pull request by Melek-C**

### CODE REVIEW

**Review by lschriml — APPROVED** [review]
fixed error, missing preferredPrefix

**Comment by lschriml** [comment]
@rays22 
Re-ran the checks, a new error, below, was found. I looked, but do not see how to fix this error:
   AssertionError: 'layo[33 chars]tle: African Population Ontology\ncontact:\n  [636 chars]tive' != 'layo[33 chars]tle: "African Population Ontology"\ncontact:\n[638 chars]tive'

**Comment by deepakunni3** [comment]
@Melek-C @lschriml The errors you see are mostly due to the fields in afpo.md not being ordered correctly.

I took the liberty of fixing the errors. See https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2587/commits/d71126182258745aae18011fc145b53ce99e4e78

**Comment by Melek-C** [comment]
Thank you @deepakunni3!

**Comment by deepakunni3** [comment]
@Melek-C Couple of observations after reviewing `afpo.md`:

- The New Ontology Request (https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2461) states that there are OWL RDF/XML, OBO, and OBO Graph JSON formats available. But in the `afpo.md` there is only one product listed. Would be good to include the others as well
- could you also provide a `title` and `description` for each product? See https://raw.githubusercontent.com/OBOFoundry/OBOFoundry.github.io/master/ontology/mp.md for inspiration

**Comment by Melek-C** [comment]
> @Melek-C Couple of observations after reviewing `afpo.md`:
> 
> * The New Ontology Request ([AfPO #2461](https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2461)) states that there are OWL RDF/XML, OBO, and OBO Graph JSON formats available. But in the `afpo.md` there is only one product listed. Would be good to include the others as well
> * could you also provide a `title` and `description` for each product? See https://raw.githubusercontent.com/OBOFoundry/OBOFoundry.github.io/master/ontology/mp.md for inspiration

Here the update : Create afpo.md #2587

**Review by deepakunni3 — APPROVED** [review]

**Comment by deepakunni3** [comment]
Thank you @Melek-C 👍

**Pull request merged**
