### PR TITLE
Updating CL obo foundry page

### PR DESCRIPTION
**Pull request by shawntanzk**
Updating CL OBO foundry page in preparation for NAR update paper

Will not merge until @dosumis goes through

### CODE REVIEW

**Comment by shawntanzk** [comment]
Fixes https://github.com/obophenotype/cell-ontology/issues/1591

**Review by matentzn — CHANGES_REQUESTED** [review]
As per convention, we can only accept usages if they point to a page that reveal a concrete usage of a CL term.. else usages are only documented in the description section. Can you provide concrete links with examples? See Mondo md file.

**Comment by shawntanzk** [comment]
whoops sorry about that, yeah there should be specific examples, will add them :)

**Review by matentzn — APPROVED** [review]
Thank you @shawntanzk 

Please fix errors and we are good to go.

**Pull request merged**
