### PR TITLE
Add publication as requested

### PR DESCRIPTION
**Pull request by edwardsnj**

### CODE REVIEW

**Comment by edwardsnj** [comment]
Fixed spaces that caused failed checks

**Comment by cthoyt** [comment]
Hi @edwardsnj does this have an "actionable" citation in a source like PubMed, PubMed Central, a DOI, or a preprint server? Right now, we're not accepting random PDF links that can't be resolved by a high-quality service for author, title, and other bibliometric metadata. Further discussion and context on why we're doing that can be found on https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1859. If none of those are available, I'd suggest uploading your article to a preprint server like arXiv

**Comment by edwardsnj** [comment]
Up to y'all, but it is a peer reviewed ICBO five-page abstract. Won't be the primary reference forever, but it is for now...

**Comment by cthoyt** [comment]
Well barring discussion about issues with peer review, we're trying to make metadata in OBO Foundry actionable. Even if we can't accept an ICBO PDF link (petitioning them to do a better job archiving their content is a different discussion too), let me know if there's an issue with the alternative to upload to arXiv

**Comment by matentzn** [comment]
@edwardsnj we have decided to require "actionable, persistent identifers" for publications. Can you upload your paper to Zenodo and share the doi?

**Review by matentzn — APPROVED** [review]

**Pull request merged**
