### PR TITLE
Update obi.md

### PR DESCRIPTION
**Pull request by jamesaoverton**
- add publication
- add usages: IEDB

I'd like to leave this open for one week, so other OBI developers can add their own usages.

### CODE REVIEW

**Comment by rvita** [comment]
This is the google sheet of projects that use OBI: https://docs.google.com/spreadsheets/d/1DOBtHHjEQQYdXf9TDiorOYXJZPqMRsV54FqEKs3IQZ4/edit?usp=sharing

**Comment by DanBerrios** [comment]
> This is the google sheet of projects that use OBI: https://docs.google.com/spreadsheets/d/1DOBtHHjEQQYdXf9TDiorOYXJZPqMRsV54FqEKs3IQZ4/edit?usp=sharing

This is just an exemplar table....

**Comment by DanBerrios** [comment]
Will leave this open to collect more usage data repositories and examples of usage.

**Review by matentzn — APPROVED** [review]
Excellent! I checked the links, looking great!

**Pull request merged**
