### PR TITLE
mark micro as inactive

### PR DESCRIPTION
**Pull request by cmungall**
https://github.com/carrineblank/MicrO/issues

### CODE REVIEW

**Comment by deepakunni3** [comment]
@cmungall Thank you for the PR.

Would it be possible to detail the reasons for making MicrO inactive?
Is it because there has been no activity in their repo since 2018?

@carrineblank Requesting your review on the changes from this PR

**Comment by deepakunni3** [comment]
After attempt to contact the owner via email, this PR is scheduled for merge on the June 2 according to https://obofoundry.org/docs/SOP.html#META

**Comment by nlharris** [comment]
> After attempt to contact the owner via email, this PR is scheduled for merge on June 2 according to https://obofoundry.org/docs/SOP.html#META

**Review by matentzn — APPROVED** [review]

**Comment by cthoyt** [comment]
woohoo! I highly applaud the effort of increasing transparency of resource status in OBO Foundry.

**Pull request merged**
