### PR TITLE
Removing mention of 2ary 3ary contacts

### PR DESCRIPTION
**Pull request by cmungall**
This text makes no sense as we only allow a single contact, see #1007 and http://obofoundry.org/principles/checks/fp_011

### CODE REVIEW

**Comment by nataled** [comment]
We don't restrict the number of contacts, just the type of contacts. Each must be an individual. I suggest removing the sentence as you say, but adding this sentence to the end of the paragraph:

Note that alternative contacts can be designated in case the primary contact is unavailable. However, as for the primary contact, each alternative contact must be an individual.

**Comment by jamesaoverton** [comment]
@nataled I'm pretty sure that all the registry entries have exactly one contact (with the exception of orphaned projects, which have no contact). The JSON schema and other code/tests expect exactly one contact. So there's a disconnect.

**Comment by nataled** [comment]
The automated checks are supposed to follow the principle, not the other way around. This principle has been discussed by the EWG and vetted by the Ops committee. If we want to change it, it should be done through the proper discussion channels.

**Comment by jamesaoverton** [comment]
I hear what you're saying @nataled, but unlike the recent dashboard work, the tooling around a single contact goes back to our migration to GitHub, around July 2015, and all 200+ registry entries conform to it. @cmungall can correct me if I'm mistaken about that.

**Comment by nataled** [comment]
I don't doubt you. Just pointing out that we don't make ad hoc decisions of the type that will actually change the principle. Even though there are good reasons for keeping it as is, I don't personally object to the change proposed--but I do object to changing it without discussion.

**Comment by cmungall** [comment]
James is correct

**Comment by cmungall** [comment]
In fact it predates that. Always been single contact.

**Comment by mellybelly** [comment]
Registry entries have one contact. I had emailed all of the contacts a number of years ago because we had a lot of listserv entries/multiple entries that were dead, at that time we confirmed/updated all the entries in the registry as one single individual. The rationale was that given that it was a person, we'd be able to follow up more readily than a dead listserv. If we want to add other fields then that is a different issue. 

+1 on the PR.

**Comment by yongqunh** [comment]
Having alternative contacts is important in many cases when the primary contact is unavailable, esp. for the collaborative development of ontology among different groups.

**Comment by nlharris** [comment]
Sounds like it would be good to have two fields, a "Primary contact" field (with only one person) and an "Alternate contact(s)" field.

**Comment by yongqunh** [comment]
yes

**Comment by cmungall** [comment]
folks, there is a separate ticket for this that has been open since 2015:
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/73

Let's continue the discussion there. For now, this PR should be merged, to
reflect reality.

**Comment by balhoff** [comment]
In discussion at OBO Operations Committee meeting 2020-03-24, we suggest appending to the proposed text: "Note that alternative contacts can be designated in case the primary contact is unavailable. However, as for the primary contact, each alternative contact must be an individual." 

We also agreed that the metadata schema should be extended with a new field for 'alternative contacts' (or similar).

**Comment by yongqunh** [comment]
That’s good. Thanks!

**Comment by pbuttigieg** [comment]
Operations Committee call today: as this requires quite a few changes to tooling to, the question is more one on who will act on this principle change.

**Comment by nlharris** [comment]
Can this be merged?

**Comment by cmungall** [comment]
darren approved it, so yep!

**Comment by nlharris** [comment]
"Draft pull requests cannot be merged"

**Pull request merged**
