### PR TITLE
Create xl.md

### PR DESCRIPTION
**Pull request by germa**
Ontology for cross-linker reagents

### CODE REVIEW

**Comment by cmungall** [comment]
How attached are you to the xl prefix? I try to encourage longer names to avoid clashes with non-OBO prefixes. However, we have no explicit policy on this, but nevertheless I will voice my preference for something like "xlmod" (entailing IDs of the form XLMOD:nnnnn).

Thank you very much for providing the md file as a github PR, this makes things much easier. Could I also trouble you to announce your intention on obo-discuss, and provide a link to this PR? This will give a chance for the wider community to comment.

**Comment by germa** [comment]
I changed it from xl to xlmod now.
[xlmod.md.txt](https://github.com/OBOFoundry/OBOFoundry.github.io/files/361374/xlmod.md.txt)

**Comment by germa** [comment]
... and also announced it on obo-discuss

**Comment by cmungall** [comment]
Great - and will you also change the IDs to be XLMOD:nnnn?

If not then the ontology id should stay as xl

**Comment by germa** [comment]
yes, all ID's are changed now to XLMOD:nnnn

**Comment by cmungall** [comment]
> yes, all ID's are changed now to XLMOD:nnnn

Wonderful! Thanks very much for accommodating.

**Comment by cmungall** [comment]
Looks like the filename change didn't make it into the PR. I will merge the PR then move

**Pull request merged**
