### PR TITLE
Update about-OBO-Foundry.html

### PR DESCRIPTION
**Pull request by lschriml**
Updating text for ticket #1549

### CODE REVIEW

**Review by nataled — APPROVED** [review]

**Comment by cthoyt** [comment]
@nataled maybe I missed something but all I see in the diff is an addition of spurious whitespace

**Comment by nataled** [comment]
@cthoyt there is some problem with editing. I attempted to fix the issue indicated but couldn't even preview my changes, much less commit them to my own branch. As a test @lschriml tried. She was presented with the page as I had edited, and added a space, which worked (or appeared to).

I'm going to try again.

**Comment by cthoyt** [comment]
Thanks for the clarification. Good luck getting it all to work!

**Comment by nataled** [comment]
Turns out the problem was with the text I added, which was simply pulled from the original source. The URL in the "a" tag was missing a quotation mark. Once I fixed it, all was well. Awaiting review from @lschriml

**Pull request merged**
