### PR TITLE
Update stato.md

### PR DESCRIPTION
**Pull request by proccaserra**
I am the owner and maintainer of STATO.

### CODE REVIEW

**Comment by deepakunni3** [comment]
@proccaserra Thank you for updating the entry for STATO.

As per our SOP, we have to get a review from the current contact member of STATO (@agbeltran) before merging these changes.

@agbeltran Could you please review and approve this PR?

**Comment by deepakunni3** [comment]
@proccaserra The OBO Dashboard pipeline is run monthly. The next run would be on or around 21st July.

A new release of an ontology does not trigger a re-run of the dashboard. 

CC'ing @anitacaron (OBO Dashboard Maintainer).

**Comment by proccaserra** [comment]
@anitacaron @deepakunni3 thank you both for the swift replies 👍 .
@anitacaron thanks for the pointer, that looks exactly like what I was looking for. In the meantime, July 21st is not far away .

**Comment by proccaserra** [comment]
@agbeltran ?

**Review by agbeltran — APPROVED** [review]

**Comment by deepakunni3** [comment]
Thank you @agbeltran 👍

**Review by deepakunni3 — APPROVED** [review]

**Pull request merged**
