### PR TITLE
update rex.md

### PR DESCRIPTION
**Pull request by rvita**
per OBO services grant, Janna Hastings & Gareth Owen, removed contact info for rex. It will be maintained at EBI in the future, but is currently inactive. It has no homepage or license info.

### CODE REVIEW

**Comment by cmungall** [comment]
For inactive ontologies, add `activity_status: inactive`

Note that rex represents a solid serious ontology, I think we should at least preserve the version at a github repo to ensure it doesn't blink out of existence altogether, @G-Owen @jannahastings do you have interest in doing this?

**Comment by cmungall** [comment]
Ah I see that @jannahastings provided an answer here: #470 

We should at least make sure we are pointing to the maintained archive at EBI

**Comment by cmungall** [comment]
@rctauber shouldn't this validation checks as the email slot is empty?

**Comment by rctauber** [comment]
@cmungall the test looks at the `ontologies.jsonld` file so it won't catch something like this until the registry files are updated. We could build a new `ontologies.jsonld` in Travis first before running the test?

**Comment by rctauber** [comment]
I could add the following to the Makefile in #781 and that would help with the conflicts, as well:

```
### Validate Configuration Files

validate: $(ONTS) | tmp/ontologies.jsonld
	./util/extract-metadata.py validate $^ && \
	./util/validate-metadata.py && \
	rm -rf tmp

# Uses temporary directory to store builds
# Without overwriting the actual build files

tmp:
	mkdir -p $@

tmp/ontologies.yml: $(ONTS) | tmp
	./util/extract-metadata.py concat -o $@.tmp $^  && mv $@.tmp $@

tmp/ontologies.jsonld: tmp/ontologies.yml
	./util/yaml2json.py $< > $@.tmp && mv $@.tmp $@
```

**Comment by jamesaoverton** [comment]
In #733 we agreed that "inactive" still requires a contact. No contact would mean "orphaned". Which applies to REX?

**Comment by rvita** [comment]
It is not orphaned. Chebi is actively trying to find someone to take it over, but currently it is in purgatory and there is no contact or responsible person.

**Comment by cmungall** [comment]
Sounds like it's orphaned. If someone comes available it can become unoprhaned but we should be trying to give an accurate picture of the ground truth

**Comment by cmungall** [comment]
Where are we with this @rctauber @rvita ?

**Comment by rvita** [comment]
It belongs to chebi & they cannot work on it at the moment. we can make it an orphan?

**Comment by matentzn** [comment]
What needs to be done here?

**Comment by jamesaoverton** [comment]
Fixed #788

**Pull request merged**
