### PR TITLE
Flip sorting-arrow direction

### PR DESCRIPTION
**Pull request by erik-whiting**
If it's decided that the arrows should point another direction that what was set in #2040, this PR will do that. Hope it's helpful!

### CODE REVIEW

**Comment by matentzn** [comment]
@balhoff if this is what you prefer I merge it - I do not mind either way!

**Comment by matentzn** [comment]
@erik-whiting THANK you for your contribution, again! :) Highly appreciated!

**Review by balhoff — APPROVED** [review]
Awesome, thank you :-)

**Comment by matentzn** [comment]
@erik-whiting can you resolve conflicts?

**Comment by erik-whiting** [comment]
@matentzn hey I'm not sure what happened. I rebased, pushed, and the PR closed itself.

**Pull request closed without merging**
