### PR TITLE
Added user for VBO

### PR DESCRIPTION
**Pull request by sabrinatoro**
@matentzn please check that it is what is needed. Thank you!

### CODE REVIEW

**Review by matentzn — APPROVED** [review]

**Comment by matentzn** [comment]
Looks fantastic!

**Comment by erik-whiting** [comment]
@nicolevasilevsky any reason to not merge this?

**Comment by matentzn** [comment]
Not that I can see. Ready to merge

**Comment by matentzn** [comment]
It was a good merge just for future reference: @deepakunni3 is responsible for the metadata. But since he is ooo atm, you filled in for him.

**Pull request merged**
