### PR TITLE
new FAQ about OBO-Dashboard

### PR DESCRIPTION
**Pull request by nlharris**
to add to the menu as a new section, "OBO Dashboard", with questions
"What is the OBO Dashboard?" and "How can I assess my ontology using the OBO Dashboard?"

(I will try to add the menu PR to this PR)

Addresses #1930

### CODE REVIEW

**Review by cmungall — CHANGES_REQUESTED** [review]
This is great

The OBook has a how-to guide on how to run the dashboard locally

https://oboacademy.github.io/obook/howto/deploy-custom-obo-dashboard/

I would suggest linking to this, but not having any detailed description here

I await @matentzn's thoughts on this - we want to think carefully about what documentation lives where, with an eye to both maintainability and not confusing our users

**Comment by matentzn** [comment]
I agree! Feel free to add a link here.

**Comment by nlharris** [comment]
I already added it to the PR (unless I messed up, which is certainly possible).

**Comment by nlharris** [comment]
how do i indicate that i addressed @cmungall's requested change?

**Comment by nlharris** [comment]
thanks, chris. can someone merge this PR? until this is merged, the new FAQ menu items get a 404.

**Pull request merged**
