### PR TITLE
Update of NOR Manager SOP

### PR DESCRIPTION
**Pull request by pfabry**

### CODE REVIEW

**Comment by cmungall** [comment]
can you normalize on newlines so it's easier to see changes?

**Comment by nlharris** [comment]
> can you normalize on newlines so it's easier to see changes?

Oh wow, yeah, what happened there that the entire document is shown as being changed? You think that's different flavors of newlines, Chris?

**Comment by nlharris** [comment]
@pfabry since the way you did the edits make it look to GitHub like every single line has changed, can you (1) avoid doing editing that way in the future, and (2) explain what you actually did change so we can comment on that? Thanks!

**Comment by matentzn** [comment]
I have recreated this PR here: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2631/files

**Pull request closed without merging**
