### PR TITLE
Update ontoneo.md

### PR DESCRIPTION
**Pull request by FernandaFarinelli**
Update ontoneo.md according to issue Fix ontoneo (#341).

### CODE REVIEW

**Comment by cmungall** [comment]
-1

This isn't right.

Sorry, something is messed up here, I don't think it's your fault.

First of all we don't have an entry for ontoneo in our purl registry:

https://github.com/OBOFoundry/purl.obolibrary.org/tree/master/config

This still works:
http://purl.obolibrary.org/obo/ontoneo/ontoneo.owl
...but it seems to be relying on an entry in the deprecated OCLC system.

We should just get you an entry in https://github.com/OBOFoundry/purl.obolibrary.org/tree/master/config

You could make a PR to do this, but we don't have good docs for this yet.

After that is done, the correct purl which is actually http://purl.obolibrary.org/obo/ontoneo.owl will redirect directly to your raw github file. You will no longer have need of the build tag

**Comment by mcourtot** [comment]
Yes - just back at office and still need to create PURLs for ontoneo and pdro. sorry about delay.

**Comment by cmungall** [comment]
purl PR here: https://github.com/OBOFoundry/purl.obolibrary.org/pull/280

**Comment by cmungall** [comment]
Looks like the upstream issue is fixed

**Pull request merged**
