### PR TITLE
register obi-base

### PR DESCRIPTION
**Pull request by cmungall**
useful for dealing with issues like https://github.com/obi-ontology/obi/issues/1375

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Sorry, I'm dragging my feet on this. I'm not entirely happy with the OBI base file, which is why we haven't advertised it widely.

**Comment by nlharris** [comment]
Should we discuss this during an OBO Operations call?

**Comment by matentzn** [comment]
No no, not necessary. We have it on our radar and it will solve itself eventually.

**Review by jamesaoverton — APPROVED** [review]
The file still needs work, but might as well advertise it.

**Pull request merged**
