### PR TITLE
Adding Dashboard Pass requirement to NOR instructions

### LINKED ISSUE #1496: update ‘make a new ontology request’ page
Add a friendly statement to ‘make a new ontology request’ page that you need to pass the ontology dashboard and indicate that we are willing to help them make the changes

### PR DESCRIPTION
**Pull request by matentzn**
As per discussions in the last OFOC call, we now require new NORs to pass the dashboard first before starting to provide feedback on content. This PR updates the documentation to that end.

fixes #1496

### CODE REVIEW

**Review by nlharris — APPROVED** [review]
Looks good.
I would capitalize the F in OBO Foundry.

**Comment by cmungall** [comment]
Think optics. Many existing ontologies including widely used fail. We now say to non-grandfathered ontologies they must pass. Grandfathered ontologies are given a free pass.

Not saying this is wrong, but let's just think how we communicate.

**Comment by matentzn** [comment]
Yeah it’s an issue. What about we honestly say that many grandfather
ontologies are currently broken, but we have a major effort of the whole
community under way to try and straighten them out - which will take a few
years? I mean this is what this is right? The truth!

**Comment by nicolevasilevsky** [comment]
I am all for being transparent - I like your suggestion, Nico.

Here are some suggested revisions to the text:

Any new ontology submitted to the OBO Foundry is now required to pass the [OBO Dashboard](http://dashboard.obofoundry.org/) quality control to ensure commitment to the OBO Foundry best practices and ensure the quality of any new ontologies. This means that the ontology cannot have any substantial errors (anything "red"). Your submitted ontology will be set up in a [provisional Dashboard](https://obofoundry.github.io/obo-nor.github.io/dashboard/index.html) as soon as the GitHub submission request is made. OBO foundry will provide support to help you fix any issues your submission might have. (Please note, existing ontologies may have "red" checks, and work is underway to update them and make them fully compliant.)

**Comment by cstoeckert** [comment]
The proposed text for requiring the Dashboard quality control looks great! My one tweak would be to modify "as soon as" in "Your submitted ontology will be set up in a provisional Dashboard as soon as the GitHub submission request is made." As long as this is a manual process there may be delays. How about "Your submitted ontology will be set up in a provisional Dashboard once the GitHub submission request is made."

**Comment by nlharris** [comment]
> How about "Your submitted ontology will be set up in a provisional Dashboard once the GitHub submission request is made."

I think "once" will be interpreted by many as "as soon as". How about weakening it even more by saying "after" instead of "once"? And maybe we should even add some caveat that this might take a week or two (?), so that submitters don't get worried and start pinging us if it hasn't happened after an hour or two?

**Review by ramonawalls — APPROVED** [review]
This looks good to me.

**Comment by nlharris** [comment]
We discussed this on the OBO Operations call today and agreed to merge this.

**Pull request merged**
