### PR TITLE
Update to.md

### PR DESCRIPTION
**Pull request by cooperl09**
fixing minor typo

### CODE REVIEW

**Review by cthoyt — APPROVED** [review]

**Review by matentzn — APPROVED** [review]

**Comment by cooperl09** [comment]
When will this change show up on the OBO Foundry site?

**Comment by cthoyt** [comment]
This shows up after somebody manually regenerates all of the derived files and makes a PR that gets merged like in https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1568. We were talking about making this a bit more automatic (e.g., using a github action triggered after a merge to the main branch) on https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1570

**Comment by matentzn** [comment]
This does not seem like an urgent change - correct me if I am wrong. Could take a month or so. Or you raise it as important!

**Comment by cooperl09** [comment]
Thanks, we can wait till the next regular update takes place.

**Pull request merged**
