### PR TITLE
OLD: Issue24

### PR DESCRIPTION
**Pull request by matentzn**
This is an old, unmerged branch. We will merge or delete this.

### CODE REVIEW

**Comment by matentzn** [comment]
@mcourtot This is an old branch, can you give us some context? Can this be deleted?

**Comment by nlharris** [comment]
Since @mcourtot hasn't responded, can we delete this?

**Comment by cthoyt** [comment]
I'd object to using the OBO Foundry as a place to store (and maintain) metadata about people. This is much better done on Wikidata or ORCID. To demonstrate in https://github.com/cthoyt/obo-community-health, I extracted all of the contact information from ontologies in OBO Foundry, map their GitHub handles through Wikidata, and display various parts about each person (again, all from public sources) here: https://cthoyt.com/obo-community-health/contacts

**Comment by matentzn** [comment]
I will delete this.

**Comment by matentzn** [comment]
Agreed @cthoyt

**Pull request closed without merging**
