### PR TITLE
remove ERO page per user request

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
close https://github.com/OBOFoundry/OBOFoundry.github.io/issues/909

### CODE REVIEW

**Review by matentzn — CHANGES_REQUESTED** [review]
I dont think this is the way to obsolete an ontology!

If you scroll down here:
http://obofoundry.org/

You will find many inactive, obsoleted ontologies. So the first question is what flags do we use for ERO:
Look at [this](https://github.com/OBOFoundry/OBOFoundry.github.io/edit/master/ontology/cmf.md) example:

```
---
layout: ontology_detail
id: cmf
title: CranioMaxilloFacial ontology
contact:
  email: engelsta@ohsu.edu
  label: Mark Engelstad
homepage: https://code.google.com/p/craniomaxillofacial-ontology/
activity_status: inactive
---

Ontology for oral & maxillofacial surgical procedures.
```

**Comment by jamesaoverton** [comment]
@matentzn is right. We can't just delete registry entries, that could break all sorts of stuff.

Issue #1126 about better documentation is (unfortunately) the best documentation we currently have on ontology status and which tags to use, specifically this comment https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1126#issuecomment-592541166.

**Comment by nicolevasilevsky** [comment]
Thank you @matentzn and @jamesaoverton - I'll fix this asap.

**Comment by nicolevasilevsky** [comment]
I think ERO should be marked inactive. I'll close this and do a separate PR.

**Pull request closed without merging**
