### PR TITLE
Add OFOC photos

### LINKED ISSUE #2193: Show photos of OBO Operations members on website?
We would like to add a bit of a more human touch to the OBO member pages.

## Do you consent on adding your picture to OBO operations committee on the website?

From our slide deck:

image

- [ ] @alanruttenberg
- [ ] @addiehl
- [ ] @phismith
- [ ] @wdduncan
- [ ] @hoganwr
- [ ] @bpeters42
- [ ] @cmungall
- [ ] @cstoeckert
- [ ] @ddooley
- [ ] @nataled
- [ ] @dosumis
- [ ] @handemcginty
- [ ] @jamesaoverton
- [ ] @zhengj2007
- [ ] @balhoff
- [ ] @lschriml
- [ ] @mbrush
- [ ] @mellybelly
- [X] @matentzn
- [ ] @nicolevasilevsky
- [ ] @nlharris
- [ ] @proccaserra
- [ ] @pbuttigieg
- [ ] @ramonawalls
- [ ] @rvita
- [ ] @beckyjackson
- [ ] @scheuerm
- [ ] @kltm
- [ ] @shawntanzk

### PR DESCRIPTION
**Pull request by matentzn**
Fixes #2193 

@cthoyt I took the liberty of hacking this into the table you made.. I have not checked how it will look yet, trying now.

I didn't have the time to look for hi-res photos, all of the ones I added are 280x220, png. Anyone who is not happy with their picture can have simply upload a higher quality one!

### CODE REVIEW

**Comment by matentzn** [comment]
> This is great! I'd suggest decreasing the max-height of the images to something smaller like 100px - they're a bit big now.

Done.

**Comment by matentzn** [comment]
> I would prefer there is an accompanying metadata check to make sure that photos exist for all members.

I think it's pretty obvious if it's missing, maybe does not merit a check?

**Comment by cthoyt** [comment]
> > I would prefer there is an accompanying metadata check to make sure that photos exist for all members.
> 
> I think it's pretty obvious if it's missing, maybe does not merit a check?

Given all of the other obvious things that are never addressed on OBO Foundry's site, I would be defensive. But don't hold up this PR on it.

**Comment by matentzn** [comment]
Lets see how it looks like.

**Review by nlharris — APPROVED** [review]
I can't tell from this how it will actually look on the web page, but as far as I can tell it seems fine. I agree with Charlie that the photo size as shown in the file here is too big, but it sounds like you already adjusted that so they will be smaller on the web page.

**Pull request merged**
