### PR TITLE
added phenotype editors mailing list

### PR DESCRIPTION
**Pull request by nicolevasilevsky**

### CODE REVIEW

**Comment by cmungall** [comment]
The value has to be a URL

**Comment by nicolevasilevsky** [comment]
The value for the mailing list is a URL, I hyperlinked it - is that what you meant?

**Comment by cmungall** [comment]
Nope, that value has to be the URL. The website takes care of hyperlinking it

**Comment by nicolevasilevsky** [comment]
sorry, I don't understand what you mean

**Comment by nicolevasilevsky** [comment]
Ok -I updated it

**Pull request merged**
