### PR TITLE
update Simon and James M's status

### PR DESCRIPTION
**Pull request by nicolevasilevsky**

### CODE REVIEW

**Review by matentzn — CHANGES_REQUESTED** [review]
Simons url should be removed - he is no longer at ebi!

**Comment by nicolevasilevsky** [comment]
done

**Review by nlharris — COMMENTED** [review]
i may have missed this new category "OBO Industry Liaison" but seems fine. are there any others who should be in that category as well?

**Review by matentzn — APPROVED** [review]

**Comment by matentzn** [comment]
I think for now, those two are a great start! Thank you!

**Pull request merged**
