### PR TITLE
Create htn.md

### PR DESCRIPTION
**Pull request by jamesaoverton**
This is the OBO registry entry for HTN. See request #878 in this repo, and PURL PR https://github.com/OBOFoundry/purl.obolibrary.org/pull/526

@cstoeckert and @aellenhicks please review this, then I'll merge both PRs.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Thanks for reviewing. I should have reviewed more carefully because I forgot that we require a contact person: name and email.

**Comment by cstoeckert** [comment]
Please make the contact. Amanda Hicks <aellenhicks@gmail.com>

**Comment by jamesaoverton** [comment]
Ok, this is live:

- http://www.obofoundry.org/ontology/htn.html
- http://purl.obolibrary.org/obo/htn.owl

Thanks for your patience!

**Comment by cstoeckert** [comment]
Thanks James!

**Comment by aellenhicks** [comment]
?Thank you.


Amanda Hicks, PhD
Assistant Professor, Health Outcomes & Biomedical Informatics
College of Medicine
University of Florida
CTRB 3226
PO Box 100219
2004 Mowry Road
Gainesville, FL  32610
p: (352) 294-5932<tel:%28352%29%20294-4197>
f: (352) 273-8703<tel:%28352%29%20273-8703>
aehicks@ufl.edu<mailto:hoganwr@ufl.edu>
________________________________

**Comment by aellenhicks** [comment]
?Thanks!


________________________________

**Pull request merged**
