### PR TITLE
Update fp-013-notification.md

### PR DESCRIPTION
**Pull request by nataled**
PR to invite wording review before making public.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
By "making public" do you mean that the next step is inviting public comment, or publishing as an official principle?

**Comment by nataled** [comment]
Publishing as an official principle.

**Comment by matentzn** [comment]
@nataled Should we try to give the SOP for publishing a new principle a bit more structure? https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2273

**Comment by nataled** [comment]
Superseded by another pull request https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2338

**Pull request closed without merging**
