### PR TITLE
Annotating ontologies with their usages

### PR DESCRIPTION
**Pull request by cmungall**
#451

### CODE REVIEW

**Comment by mmc46** [comment]
Should be reviewed by @temjones , responsible for FB ontologies now

**Comment by mcourtot** [comment]
Thanks - I just clicked the reviewer and it somehow re requested review -I don't seem to be able to edit, can you?

**Comment by mmc46** [comment]
Where is the reviewer specified? The ontologies' metadata have @temjones as the contact, and she was the last one to commit.

**Comment by mcourtot** [comment]
top right on this page. I *think* they would need to be part of the GitHub organisation to show up in the list of possible reviewers. I just sent an invitation hopefully this will work. Thanks!

**Comment by mellybelly** [comment]
It would be great for editorial group to evaluate this wrt to: http://obofoundry.org/principles/fp-009-users.html

**Comment by cmungall** [comment]
it's maybe quite hard for people who aren't used to the github system to review the whole PR as it involves additions to multiple files. We can merge and have people edit their own individual records, or have them work with us to do this on a more one-on-one basis

**Pull request merged**
