### PR TITLE
Create scdo.md

### PR DESCRIPTION
**Pull request by matentzn**
new ontology, see 
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/392

### CODE REVIEW

**Review by scdodev — CHANGES_REQUESTED** [review]
I think just to update the description to: An ontology for the standardization of terminology and integration of knowledge about Sickle Cell Disease.

**Comment by matentzn** [comment]
Cool, check again :) If you are happy, approve.

**Review by scdodev — APPROVED** [review]

**Review by scdodev — APPROVED** [review]
Look good, thanks Nico!

**Comment by jamesaoverton** [comment]
See also the PURL request: https://github.com/OBOFoundry/purl.obolibrary.org/pull/750

**Review by jamesaoverton — APPROVED** [review]

**Comment by matentzn** [comment]
@jamesaoverton thank you!

**Pull request merged**
