### PR TITLE
Get rid of redundant OBO Ops Mission page, merge non-redundant text i…

### LINKED ISSUE #2167: Reduce redundant text in OBO ops landing and mission statment page
The text on the following two pages is almost the same:

1. OBO Ops landing page: https://obofoundry.org/docs/OperationsCommittee.html
2. OBO Ops mission statement: https://obofoundry.org/docs/MissionStatement.html

I suggest taking the text out of the mission statement page and putting it on the landing page, then deleting the dedicated mission statement page. This would make the burden of reading through the site on the reader much smaller.

### PR DESCRIPTION
**Pull request by nlharris**
…nto OBO Ops landing page

Fixes #2167

### CODE REVIEW

**Comment by cthoyt** [comment]
While you're compressing things, can you also just combine the Mailing List (https://obofoundry.org/docs/MailingLists.html) into the main page

**Comment by nlharris** [comment]
How about instead if I merge https://obofoundry.org/docs/CommitteeMeetings.html, https://obofoundry.org/docs/OBOCalendar.html, and https://obofoundry.org/docs/MailingLists.html into one page? (Not sure what to call it -- OBO Operations Operations??)

I understand the desire to tighten things up, but adding lots of details (such as mailing lists) to the main page doesn't necessarily make it easier for people to navigate.

**Comment by nlharris** [comment]
and if you approve the proposal above, how about let's get this PR merged and i'll make another one for that?

**Comment by cthoyt** [comment]
Sure that’s fine, call it logistics or something like this

**Review by matentzn — APPROVED** [review]

**Comment by nlharris** [comment]
can someone merge this and i'll start a new PR with the other changes? thanks!

**Pull request merged**
