### PR TITLE
Add usage to NCBITaxon

### PR DESCRIPTION
**Pull request by anitacaron**

### CODE REVIEW

**Review by matentzn — APPROVED** [review]
Thanks!

**Comment by matentzn** [comment]
(its ok now :D but per SOP, changes to the metadata can only be merged by our metadata steward)

**Comment by anitacaron** [comment]
Sorry 😬  it was the habit. Please, if something is wrong, let me know, @deepakunni3.

**Comment by deepakunni3** [comment]
@anitacaron No worries :)

Looks good to me 👍

**Comment by anitacaron** [comment]
Thanks!

**Pull request merged**
