### PR TITLE
Fixing broken master

### PR DESCRIPTION
**Pull request by matentzn**
@lschriml please do not commit to master.. 🗡️

### CODE REVIEW

**Comment by matentzn** [comment]
Merged this to unbreak master.

**Comment by cthoyt** [comment]
Can we fix this problem? This is the second time it happened…

**Comment by matentzn** [comment]
Sorry my bad, I had fixed it (by adding branching rules) but the problem is, it is really inconvenient for me to not being able to overwrite the branching rules at all. I sometimes have to deactivate them for a minute, and forgot to activate them again. Now they are in.

**Comment by lschriml** [comment]
Apologies @matentzn  -- Thank you !! 
       Can we disable the 'edit' button on the OBO Foundry pages, and provide a link instead for editing via a pull request ?

Cheers,
Lynn

**Comment by matentzn** [comment]
Not your fault, was mine. Its fine now!

**Pull request merged**
