### PR TITLE
Update mp.md

### PR DESCRIPTION
**Pull request by sbello**
adding link to mp-base.owl file in product list

### CODE REVIEW

**Comment by matentzn** [comment]
@cmungall @jamesaoverton @balhoff 
This raises the question for me whether base files should be registered directly? If we do that we should do it everywhere.

**Comment by sbello** [comment]
@matentzn I added this in response to @cmungall comments during the COB workshop. If we don't want to list these here that is fine. On the other hand should we list all the products of the MP release? I worry slightly that this will confuse users as to which is the preferred release file for using the ontology? Currently on the MGI ftp site we have only the 3 versions of the mp file (obo, owl and json) as these are what we would prefer most users of the ontology to consume. The other files really are for a smaller subset of users.

**Comment by matentzn** [comment]
You were totally right and amazingly proactive to do this :) I just want to get a sense whether `products` is meant just for the primary products (mp.owl, mp.obo, mp.json) or whether we should include all products we consider primary; Nothing for you to worry about - unless of course you have an opinion!

**Comment by jamesaoverton** [comment]
This would be a change. I don't know what the corresponding PURL for `mp-base.owl` (specified here) would be. So far we have been scrupulous about reserving the top-level name space for http://purl.obolibrary.org/obo/{idspace}.{format}

**Comment by matentzn** [comment]
All the base files are currently tagged and available as http://purl.obolibrary.org/obo/{idspace}/{idspace}.{format}; I would not want to change that to http://purl.obolibrary.org/obo/{idspace}.{format}! Does this mean mp-base is conceptually not a `primary` product?

**Comment by sbello** [comment]
So should this have followed the GO pattern? Although oddly hovering over the link on the GO page shows a link ...go/go-base.owl but the link resolves http://current.geneontology.org/ontology/go-base.owl (although clicking on this link causes the tab to crash, maybe it works if you just save the link). If the text needs to be changed to mp/mp-base.owl to make the distinction that this is not a 'primary' product that is fine with me.

**Comment by matentzn** [comment]
Yeah lets wait to here from @cmungall about this - I dont think this is important to MP users; mp-base should really only be relevant for people that know what they are doing! And they know where they can find it!

**Comment by sbello** [comment]
Fine with me. Do you want me to close the pull request?

**Comment by matentzn** [comment]
Lets leave it open for a few days and see whether others have an opinion!

**Comment by balhoff** [comment]
I think all products should be listed, but described. There is a lot of info on the different products in the GO listing: http://obofoundry.org/ontology/go.html [[source]](https://raw.githubusercontent.com/OBOFoundry/OBOFoundry.github.io/master/ontology/go.md)

I think for mp-base it should `mp/mp-base.owl`.

**Comment by matentzn** [comment]
@balhoff @sbello I have now [adjusted the markdown](https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1260/files) to Jims suggestions. What do you think? Other than `taste` does anyone have any arguments against this? @cmungall @jamesaoverton

**Comment by sbello** [comment]
Thanks @matentzn ! I think it looks good.

**Comment by cmungall** [comment]
Need any more input from me?

**Comment by matentzn** [comment]
If you are fine with this general approach no :)

**Review by jamesaoverton — APPROVED** [review]
I think `mp/mp-base.owl` is good, and so are the descriptions.

**Review by matentzn — APPROVED** [review]

**Pull request merged**
