### PR TITLE
add logo

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
not sure if this is the correct way to do this!

cc @cmungall

### CODE REVIEW

**Review by matentzn — APPROVED** [review]

**Comment by matentzn** [comment]
It is. I changed the logo to make it a bit smaller.. maybe we need to make it even smaller, but that is independent of this pr

**Comment by matentzn** [comment]
Also, always be careful to reference the `raw` file - not the github page of the file!

**Comment by nicolevasilevsky** [comment]
> It is. I changed the logo to make it a bit smaller.. maybe we need to make it even smaller, but that is independent of this pr

how did you make it smaller?

It looks good, but I agree, smaller would be better.

**Comment by matentzn** [comment]
I just opened it in an image editor and made it smaller.

**Comment by matentzn** [comment]
Like this: 

1. git pull:
2. open this file https://github.com/monarch-initiative/mondo/blob/master/docs/images/mondo_logo_black-stacked-small.png in Mac preview
3. Make it smaller


but to be honest,  its not sooo bad :) I like the big logos!

**Comment by nicolevasilevsky** [comment]
thanks Nico! let's just leave it as is :)

**Pull request merged**
