### PR TITLE
Update how-do-i-register-my-ontology.md

### PR DESCRIPTION
**Pull request by nicolevasilevsky**
addresses https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1246

### CODE REVIEW

**Review by nlharris — COMMENTED** [review]
Thanks for tackling this! Are we going to revise /docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html to be simple instructions? I think maybe it would make more sense to make this page (faq/how-do-i-register-my-ontology.md) the simple instructions, and make it easier to find (not just in the FAQ menu). Then we can change the Policy_for_OBO_namespace page to be more about that specific technical stuff, with prominent pointers to the how-do-i-register page. What do you think?

**Comment by nicolevasilevsky** [comment]
great idea! I'm working on the revise /docs/Policy_for_OBO_namespace_and_associated_PURL_requests.html page now, I'll submit the PR shortly.

I'll work on updating the FAQ further next.

**Comment by nicolevasilevsky** [comment]
I renamed this page to:
How do I submit my ontology?

**Comment by nlharris** [comment]
Nicole and I discussed this and decided that we don't need to ask ontology owners to sign up for the mailing list, so she's going to take that out.

**Review by nlharris — APPROVED** [review]

**Comment by jamesaoverton** [comment]
We have always required that ontology maintainers be subscribed to the obo-discuss mailing list. I consider that critically important.

**Comment by matentzn** [comment]
I agree, this is very important - otherwise there is no way to contact the OBO sphere in a simple way to announce changes! Also, such changes to process should always go before the operations committee I think!

**Comment by nlharris** [comment]
Sorry, Nicole and I should have waited for more feedback before making that change.

Are we really checking that owners of new ontologies are signed up for the mailing list? My impression was that all communication with them was through the GitHub issues. Anyway, even if they do need to sign up for the mailing list, should that happen after their ontology is accepted? Seems mean to make someone join the list only to reject their ontology.

**Comment by nicolevasilevsky** [comment]
No worries, Nomi - I wasn't aware of the policies, we are learning the hard way, I guess. :)

I will keep working on the fixes now.

**Comment by jamesaoverton** [comment]
Submitters are asked to send an email to obo-discuss when they submit their request, notifying the larger community about their submission, and giving everyone a few weeks to provide feedback. The mailing list has a much larger reach than the GitHub issues. The key benefit of the mailing list discussion is that submitters often find out about related work and potential collaborators.

To send an email to obo-discuss, first you need to request joining the list. So that step ensures that submitters are on the list.

**Comment by nlharris** [comment]
> To send an email to obo-discuss, first you need to request joining the list. So that step ensures that submitters are on the list.
But when evaluating new ontology GitHub issues, do you check that the requester is on the obo-discuss list?

**Comment by matentzn** [comment]
We don't always, but that should really be on our new review checklist. People should really send an email to obo discuss..

**Comment by nlharris** [comment]
Remind me where the review checklist is?

**Comment by matentzn** [comment]
https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/docs/RegistrationChecklist.md

Dont think its linked from anywhere yet

**Pull request merged**
