### PR TITLE
Update actions

### PR DESCRIPTION
**Pull request by deepakunni3**
This PR does the following:
- tag the the metadata steward for review when creating a PR after 'Build derived files' action
- add conditional check to skip QC and tests if the actions are triggered from changes introduced by 'github-actions' bot

The latter should prevent actions from running immediately after 'Build derived files' action.

**Note:** The skip only applies when 'github-actions' bot commits files and creates a PR. All other user actions will still trigger the checks for QC and tests.

### CODE REVIEW

**Comment by cthoyt** [comment]
@deepakunni3 is it necessary to have it tag you in addition to assigning you? like don't those both show up in your inbox the same?

WRT the other actions, this is fine.

**Comment by deepakunni3** [comment]
Yes, but I **think** tagging me adds me as a reviewer to this PR. 
Assigning me just assigns the PR to me (without adding me as a reviewer).

**Comment by deepakunni3** [comment]
@cthoyt Thanks for the sanity check. 
Yes, tagging in the body of the PR doesn't help.

**Review by matentzn — APPROVED** [review]
Interesting solution! I am fine with this!

**Pull request merged**
