### PR TITLE
Ready for review: update names for pages (back to previous names)

### PR DESCRIPTION
**Pull request by nicolevasilevsky**

### CODE REVIEW

**Comment by matentzn** [comment]
Too difficult now to review this. Does this reinstate the old filenames and links?

**Comment by nicolevasilevsky** [comment]
It should, yes

**Review by matentzn — APPROVED** [review]
@nicolevasilevsky Thx!

**Comment by jamesaoverton** [comment]
I haven't had time yet, but when I do my plan is to run Jekyll locally and browse the site, following the instructions here: https://github.com/OBOFoundry/OBOFoundry.github.io#generation-of-downstream-artefacts

```
git pull
make
jekyll server
## open 127.0.0.1:4000 in a web browser and spot-check changes
```

**Comment by matentzn** [comment]
Lets have @jamesaoverton have a peak at this, but he will also just trust that the links are ok I assume :) Thank you!

**Review by jamesaoverton — APPROVED** [review]

**Review by nlharris — APPROVED** [review]

**Pull request merged**
