### PR TITLE
Automated check of passing NOR dashboard

### PR DESCRIPTION
**Pull request by cthoyt**
As a follow-up to #2277, this PR adds an automated check that new ontologies pass the NOR dashboard. Specifically, it checks that 1) the ontology is in the [NOR dashboard configuration](https://raw.githubusercontent.com/OBOFoundry/obo-nor.github.io/master/dashboard/dashboard-results.yml) and 2) that the summary status is `PASS` for all checks *except* for FP09 (usage)

### CODE REVIEW

**Comment by nlharris** [comment]
Thanks for doing this. My understanding is that new ontologies are allowed to FAIL the "usage" principle, though not any others. I suggested that the dashboard could change the "fail" for insufficient usage (pink) to a "warn" (yellow) so that we don't have to worry about making an exception for this one principle, but I did not prevail. So you may need to put in some logic about "all fields must be PASS except usage" to make your automated check match the current requirements.

**Comment by cthoyt** [comment]
@nlharris i'm sorry you were unsuccessful with that, I agree totally... now this just means that the OBO Dashboard status is not useful...

**Comment by matentzn** [comment]
The problem is that usage is required _full stop_, so we can't make it yellow. Its red. Any OBO ontology that wishes to pass the dashboard must pass that check!

The real question is if a usage must be recorded as a condition for registering a new ontology - here the vote was _no_. We could revisit this, but the threshold for what counts as a usage is pretty high, and its hard to see how more recent ontologies would be able to pass it (you need to provide a public link to a resources that resolves to a page mentioning an ID in your ontology). I can be swayed both ways. We could also relax for what counts as "evidence for usage" and make it required for NOR as well!

I have opened an issue about this here: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/2281

**Comment by cthoyt** [comment]
I've updated the look inside the results rather than use the top-level summary. The code is now allowing the usage check (FP09) to fail, while requiring all others do not.

**Review by erik-whiting — APPROVED** [review]

**Pull request merged**
