### PR TITLE
Added link to purl entry in github. Fixes #181

### LINKED ISSUE #181: Add Edit purl metadata button on ontology_detail pages
Analogous to the edit main metadata button.

Adding the button should be trivial. But also need to integrate with main documentation

### PR DESCRIPTION
**Pull request by cmungall**
@jamesaoverton look OK?

### CODE REVIEW

**Comment by cmungall** [comment]
This is how it looks

screen shot 2015-11-30 at 12 39 02 pm

**Comment by jamesaoverton** [comment]
The link is correct. In my `simpler` branch the filename uses the IDSPACE casing, but I'll worry about that later.

Maybe the button label should be plural: "PURLs"?

**Comment by cmungall** [comment]
Yes, PURLs is better

Hmm, could get confusing if one is IDSPACE case

**Comment by jamesaoverton** [comment]
The registry YAML files should have a field for the exact case-sensitive IDSPACE. Is this it? `preferredPrefix: FBdv`

In any case, I don't need that field right now, and there's an `idspace` field in the PURL YAML files that I've manually checked for most of our ontologies.

**Pull request merged**
