### PR TITLE
Change ontobee URL

### LINKED ISSUE #2027: Use https version of Ontobee.org
At the top of the obofoundry.or webpage: 
https://obofoundry.org/
there is a search bar. 

current it uses http version of ontobee. for example, when searching for term 'vaccine', it goes to the insecure webpage:  
http://www.ontobee.org/search?ontology=&submit=Search+terms&keywords=vaccine

Since ontobee.org has recently updated to use https instead of http, I would suggest changing
http://www.ontobee.org/
to: 
https://ontobee.org/
such as: 
https://ontobee.org/search?ontology=&submit=Search+terms&keywords=vaccine

Thanks, Oliver

### PR DESCRIPTION
**Pull request by matentzn**
Fixes #2027

### CODE REVIEW

**Review by yongqunh — COMMENTED** [review]
I checked, and they look all good. Thanks! 
- Oliver

**Review by yongqunh — APPROVED** [review]

**Review by nlharris — APPROVED** [review]
at a quick glance, this looks fine to me, though i can't verify that you caught all the instances of http://[www].ontobee.

**Comment by matentzn** [comment]
I didn't catch all of them, about 15 ontology pages have links to the old ontobee.. since these will continue to work, it's fine. People can fix their own metadata when it is necessary!

**Comment by yongqunh** [comment]
Looks great! Thanks!

**Pull request merged**
