### PR TITLE
Update po.md

### PR DESCRIPTION
**Pull request by cooperl09**
Fixing the Planteome logo

### CODE REVIEW

**Review by nlharris — APPROVED** [review]

**Comment by nlharris** [comment]
to fix https://github.com/Planteome/plant-ontology/issues/726

**Comment by cooperl09** [comment]
I am not sure if this will work? Still not resolving

**Comment by matentzn** [comment]
@cooperl09 you need to wait until our Metadata steward gets to merge https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2593

**Comment by cooperl09** [comment]
@matentzn Any idea when this will get merged in? It is still not resolving

**Comment by balhoff** [comment]
@cooperl09 I think everything was merged, but the link was to the GitHub page about the image rather than directly to the image. I made a change here: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2637

**Pull request merged**
