### PR TITLE
Add tracker to xlmod.md

### PR DESCRIPTION
**Pull request by matentzn**

### CODE REVIEW

**Comment by jamesaoverton** [comment]
I was expecting https://github.com/HUPO-PSI/psi-mod-CV/issues based on the PURL config https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/mod.yml

**Comment by matentzn** [comment]
Are you sure? seems a different ontology?

http://obofoundry.org/ontology/mod.html

**Comment by matentzn** [comment]
I used it because that repo also has the xlmod "ontology"

**Comment by matentzn** [comment]
https://github.com/HUPO-PSI/mzIdentML/tree/master/cv

**Comment by jamesaoverton** [comment]
Yes, my mistake.

**Review by jamesaoverton — APPROVED** [review]

**Pull request merged**
