### PR TITLE
add license to hp.md

### PR DESCRIPTION
**Pull request by rvita**
per obo services grant, updated metadata - added license

### CODE REVIEW

**Comment by jamesaoverton** [comment]
It's not clear to me that this is an open source license, and it does not conform to the current wording of OBO Principle 1.

**Comment by cmungall** [comment]
cc @drseb @pnrobinson @mellybelly

**Comment by jamesaoverton** [comment]
Any updates on this license?

**Comment by pnrobinson** [comment]
We continue to have this license
https://hpo.jax.org/app/license

**Comment by cmungall** [comment]
@jamesaoverton I propose we merge since the PR accurately reflects the state of affairs

**Comment by cmungall** [comment]
Note that I added the HPO license to the list of available licenses, as the travis checks were failing:

https://github.com/OBOFoundry/OBOFoundry.github.io/pull/802/files#diff-dad1eab43f23840142505172a137e50c

**Pull request merged**
